### ISSUE TITLE
Authentication failed - MacOS - After following "Preventing "Authentication failed" on some systems" recommendations

### ISSUE THREAD

**Issue by ThisIzATriumph** [trustmaster/gkeep2notion#16]
Hi, thank you for your work! 
I'm getting the following error after following the instructions. 

`Loading access token from keyring
Logging into Google Keep
Password: 
Authenticating, this may take a while...
Authentication failed
('BadAuthentication', None)`

The 'pip3 install -r requirements.txt' command leads to the following: 
'ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
notion-sdk-py 0.0.1 requires chardet==4.0.0, but you have chardet 3.0.4 which is incompatible.
notion-sdk-py 0.0.1 requires requests==2.25.1, but you have requests 2.23.0 which is incompatible.
notion-sdk-py 0.0.1 requires urllib3==1.26.4, but you have urllib3 1.25.11 which is incompatible.
Successfully installed chardet-3.0.4 urllib3-1.25.11
WARNING: Skipping /usr/local/lib/python3.11/site-packages/certifi-2023.7.22-py3.11.egg-info due to invalid metadata entry 'name'
WARNING: Skipping /usr/local/lib/python3.11/site-packages/certifi-2023.7.22-py3.11.egg-info due to invalid metadata entry 'name''

So there might be a conflict in dependencies. However installing chardet==4.0.0, requests==2.25.1 and urllib3==1.26.4, doesn't fix it. The warning on certifi stays as well. 

Aside from these, the solution concerning the CAPTCHA problem leads to a dead google link. I'm not certain why, can it be that CAPTCHA authentication is outdated for google accounts?

**Comment by shaneholloman** [comment]
watching

**Comment by hexadeciman** [comment]
I figured out how to make it work, culprit is gkeepapi dependency which requires running the script inside a docker container.
I'll submit a PR.

Edit: Done #19

**Comment by trustmaster** [comment]
Fixed in #19, but requires Docker to run.
