### ISSUE TITLE
Add an instruction for generating app password for google acc

### ISSUE THREAD

**Issue by mArTi3-github** [trustmaster/gkeep2notion#3]
I have 2-step verification in my google account so I was always getting an error "Authentication failed" even after applying both advises in 'Preventing "Authentication failed" on some systems' section.
I solved this issue by generating app password for google account using [this instruction](https://support.google.com/accounts/answer/185833) and putting generated password into script's prompt.
I think it might be good to add this advice to readme.

**Comment by pushp1997** [comment]
@trustmaster  Please review the PR. the steps have been added to the readme.

**Comment by mArTi3-github** [comment]
@pushp1997 everything is correct, thank you!
