### ISSUE TITLE
Add support for reminders in Keep

### ISSUE THREAD

**Issue by pushp1997** [trustmaster/gkeep2notion#6]
This is a feature request to support the transfer of reminders and recurring reminders to notion.

**Comment by trustmaster** [comment]
Hey @pushp1997 ! Do you have an idea of how these reminders could be represented in Notion? (Disclaimer: I'm not a power Notion user myself, I mostly use it for note taking)

**Comment by pushp1997** [comment]
I just read [this](https://thomasjfrank.com/how-to-create-recurring-tasks-repeat-due-dates-in-notion/). Apparently, recurring reminder are not supported out of the box in Notion, though the author has given an alternative way to achieve the same. See if this helps!

**Comment by trustmaster** [comment]
As Notion doesn't support it, there no plans to add reminders to this tool either. Unless somebody provides a pull request.
